config/routes.rb
Rails.application.routes.draw do
  get 'maps/demo_basic'  => 'maps#demo_basic'
  get 'maps/demo_filtering'  => 'maps#demo_filtering'

  namespace :api do
    namespace :v1 do
      get 'search' => 'search#index'
    end
  end

  root to: 'maps#demo_basic'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :year, numericality: { greater_than_or_equal_to: 2006 }
  validates :make, :model, presence: true
end

app/controllers/api/v1/search_controller.rb
module Api::V1
  class SearchController < ApplicationController

    def index
      vehicles = Vehicle.all
      render json: vehicles, status: :ok
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def demo_basic
  end

  def demo_filtering
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
    <nav class="flex items-center justify-between flex-wrap bg-blue p-6">
      <div class="flex items-center flex-no-shrink text-white mr-6">
        <span class="font-bold text-xl">rails5-gmap-stimulus-tailwind demo</span>
      </div>
      <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-blue-lighter border-blue-light hover:text-white hover:border-white">
          <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
      </div>
      <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <div class="text-sm lg:flex-grow">
          <%= link_to "Basic", maps_demo_basic_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4" %>
          <%= link_to "Filtering", maps_demo_filtering_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4" %>
          <%= link_to "Source Code", "https://github.com/rdeguzman/rails5-gmap-stimulus-demo", class: "block mt-4 lg:inline-block lg:mt-0 text-blue-lighter hover:text-white mr-4", target: "_blank" %>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5GmapDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>

  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <div class="container mx-auto">
      <%= yield %>
    </div>

  </body>
</html>

app/views/maps/demo_basic.html.erb
<h2 class="title">Demo Map Basic</h2>

<div class="sub-title">
  Displays a basic google map, fetches sample.json, and add the markers 
</div>

<div id="fullmap"
     data-controller="map-basic"
     data-map-basic-url="/api/v1/search">
</div>

app/views/maps/demo_filtering.html.erb
<h2 class="title">Demo Map filtering</h2>

<div class="sub-title">
  Demo Basic with filters based on json attribute.
</div>

<div data-controller="map-filters" data-map-filters-url="/api/v1/search">

  <div class="inline-flex mb-1">
    <label>Show Only:</label>

    <button    id="btnAll"
            class="btn btn-blue btn-group rounded-l"
      data-action="map-filters#all">ALL</button>

    <button    id="btnAvailable"
            class="btn btn-blue btn-group"
      data-action="map-filters#available">Available</button>

    <button    id="btnInUse"
            class="btn btn-blue btn-group rounded-r"
      data-action="map-filters#inUse">InUse</button>

  </div>

  <div id="mapdiv"></div>
</div>